# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from helpers import type

# Setup
driver = webdriver.Firefox()
driver.maximize_window()
driver.implicitly_wait(10)
# Constants:
DELAY = 0.2
# Inputs
email = "charles6huang@gmail.com".split("@")
password = "Jaygay123"
username = "aoeuaoeuuaoeuk"
account_total = 5


for acc_num in range(account_total):
    # Navigate to register page
    driver.get("https://playvalorant.com/en-us/")
    assert "VALORANT" in driver.title
    # Click "play free" button
    driver.find_element(By.CSS_SELECTOR, ".HomeHero-module--downloadButton--3BblN .PrimaryButton-module--label-text--23ce5").click()
    # Click "make account" button
    driver.find_element(By.CSS_SELECTOR, "button.PrimaryButton-module--default--2alKM").click()

    # Put in email
    time.sleep(1)
    email_in = driver.find_element_by_name("email")
    type(email_in, email[0]+username+'@'+email[1])
    time.sleep(1)
    driver.find_element(By.NAME, "email").send_keys(Keys.ENTER)

    # Put in birthdate
    driver.find_element(By.NAME, "date_of_birth_day").send_keys("19")
    time.sleep(1)
    driver.find_element(By.NAME, "date_of_birth_month").send_keys("09")
    time.sleep(1)
    driver.find_element(By.NAME, "date_of_birth_year").send_keys("1999")
    time.sleep(1)
    driver.find_element(By.NAME, "date_of_birth_year").send_keys(Keys.ENTER)

    # Put in username and password
    time.sleep(1)
    username_in = driver.find_element(By.NAME, "username")
    type(username_in, username+str(acc_num))
    driver.find_element(By.NAME, "username").send_keys(Keys.ENTER)

    time.sleep(1)
    password_in = driver.find_element(By.NAME, "password")
    type(password_in, password)
    driver.find_element(By.NAME, "confirm_password").click()
    time.sleep(1)
    password_in = driver.find_element(By.NAME, "confirm_password")
    type(password_in, password)
    driver.find_element(By.CSS_SELECTOR, ".mobile-button").click()
    # Log back out
    driver.find_element(By.LINK_TEXT, "PLAY NOW").click()
    driver.find_element(By.CSS_SELECTOR, ".PrimaryButton-module--default--2alKM .PrimaryButton-module--label-text--23ce5").click()
    driver.find_element(By.CSS_SELECTOR, ".riotbar-summoner-info:nth-child(1) > .riotbar-summoner-name").click()
    driver.find_element(By.CSS_SELECTOR, ".riotbar-account-link").click()
    vars["check"] = driver.execute_script("return arguments[0] + 1", vars["check"])



